### ISSUE TITLE
[feature request] subdirectory for kernel files

### ISSUE THREAD

**Issue by basegpu** [OP-DSL/OP2-Common#119]
in a project using *OP2*, all source files that are translated are located in a directory `src`.

In the same directory I put all header files with `inline void kernelXXX(){...}`, and accordingly the generated implementation files of the kernels for the different backends are there as well.

Now, would it be possible to let the translator know a subdirectory e.g. `src/kernels` where all the kernel header files are located? The generated kernels should be put there as well and the includes in the translated source should be updated as well.

For large projects with many source files and many more kernel files this functionality would increase the flexibility from an organisational point of view.

**Comment by reguly** [comment]
I have been meaning to do this for a while... Please have a look at the feature/subdirs branch. I patched the code generators, but I still have some issues with CMake: when a file, e.g. openmp/update_kernel.cpp #include "update.h", the compiler doesn't find it because it's not in the same directory.

**Comment by reguly** [comment]
Fixed, please discuss further in #120
